### ISSUE TITLE
Please add support $numberLong

### ISSUE THREAD

**Issue by leotu** [vert-x3/vertx-mongo-client#103]
Ref: 
https://docs.mongodb.com/manual/reference/mongodb-extended-json/#numberlong
http://mongodb.github.io/mongo-java-driver/3.4/upgrading/

JsonObjectCodec.java  still not support "$numberLong", 
when document is
```json
{
  "_id" : "32034ffb-9ab8-4dce-bf95-591053bd53d4",
  "_seqCounter" : {
    "$numberLong" : "7279"
  },

}
```
That write to MongoDB, it throws java.lang.IllegalArgumentException: Invalid BSON field name $numberLong

But  if I change to
 ```json
{
  "_id" : "32034ffb-9ab8-4dce-bf95-591053bd53d4",
  "_seqCounter" :  7279

}
```
That would be stored as BsonType.INT32 not the BsonType.INT64 but my data is Long type !

Note: There is alos a new type $numberDecimal (https://docs.mongodb.com/manual/core/shell-types/#numberdecimal)

Found this issue:
https://github.com/vert-x3/vertx-mongo-client/pull/4

And code ref. maybe helpfully:
https://github.com/mongodb/mongo-java-driver/blob/master/bson/src/main/org/bson/json/JsonReader.java

https://github.com/mongodb/mongo-java-driver/blob/master/bson/src/main/org/bson/json/ExtendedJsonInt64Converter.java

https://github.com/mongodb/mongo-java-driver/blob/master/bson/src/main/org/bson/json/ExtendedJsonDecimal128Converter.java

**Comment by lukjel** [comment]
+1
Any chance to make it available soon?

**Comment by karianna** [comment]
@lukjel We're hoping for a community contributed PR for this functionality :-)

**Comment by razzbee** [comment]
NumberDecimal implementation seems to be missing

**Comment by fusseybill** [comment]
I am trying to use the vertx-mongo-client to write a long to a database. 
`
compile group: 'io.vertx', name: 'vertx-mongo-client', version: '4.0.0-milestone2'
`

I can see you have implemented some code in "AbstractJsonCodec" to write a long, however, I can see that the Class is never used by the client.

(AbstractJsonCodec. line 83)
`
protected void writeValue(BsonWriter writer, String name, Object value, EncoderContext ctx) {
...
case INT64:
        writeInt64(writer, name, value, ctx);
        break;
...
}
`

Is the long implementation still in development? because this feed is closed?

**Comment by kostya05983** [comment]
Hello, @fusseybill, No, the development is over, you can find an example with write a NumberLong in [JsonObjectCOdecTest](https://github.com/vert-x3/vertx-mongo-client/blob/master/src/test/java/io/vertx/ext/mongo/impl/codec/json/JsonObjectCodecTest.java). Client uses child of AbstractJsonCodec the JsonObjectCodec.
