### ISSUE TITLE
Knowing if the client is connected

### ISSUE THREAD

**Issue by mszmurlo** [vert-x3/vertx-mongo-client#181]
Hi,

How to know that the client is connected on the server ? If the credentials are wrong, a `com.mongodb.MongoSecurityException` is thrown by the **mongodb driver** and it is not possible to catch it in the code. I'm aware of [this reply](https://github.com/vert-x3/vertx-mongo-client/issues/147) and some other on SO, yet the topic is really painful as once the client is created the only way to know that it is connected is to issue a query and wait for either the reply or a timeout.

Wouldn't is be possible to create a `isConnected()` method in `MongoClient` ? Even if dirty, it couldn't be worse than issuing a request and waiting for a time out without being able to say if the failure is due to bad credentials or because the server is down...

I'm working with vertx and mongo-client 3.5.4.

**Comment by AlexeySoshin** [comment]
I think that like some DB clients this client should issue no-op check, like `SELECT 1` and "die" if no-op fails. Opinions?

**Comment by mf81bln** [comment]
Since this is still open... I'd suggest to just implement a health check and invoke the mongodb "ping" command.

- https://vertx.io/docs/vertx-health-check/java/
- https://docs.mongodb.com/manual/reference/command/ping/

```
public void handle(final Promise<Status> promise)
{
    mongoClient.runCommand("ping", new JsonObject().put("ping", 1))
        .onFailure(event -> promise.complete(Status.KO()))
        .onSuccess(event -> promise.complete(Status.OK()));
}
```

Not sure if just the "ping" command should be implemented in the MongoClient as a "isConnected" method or if it would be a better idea to leave this to the application implementation (as health check).

**Comment by mszmurlo** [comment]
That makes sense

**Comment by vietj** [comment]
perhaps this could be documented in the mongo db vertx documentation ?
