### ISSUE TITLE
there is no way to store objects of mongo types Date or ISODate

### ISSUE THREAD

**Issue by ashertarno** [vert-x3/vertx-mongo-client#6]
since Json.checkAndCopy() does not allow Date/DateTime/Timestamp etc objects to be set through JsonObject.put(), there is no way to store objects of mongo types Date and ISODate.

**Comment by meshuga** [comment]
+1

**Comment by michalig** [comment]
+1
There is pull request for this issue already:
https://github.com/vert-x3/vertx-mongo-client/pull/4

... but after having quick look at it I think I know why it wasn't merged ;)

**Comment by sfitts** [comment]
Saving null's is also broken (and fixed in the PR).

@michalig -- I'd be interested to know why -- I pulled the code and it appears to correctly solve both issues.  It also adds tests (which is good), so it looks reasonable to my eye.  However, I'm new around here and trying to learn the expectations, so this would be good general knowledge.

**Comment by andyhedges** [comment]
+1 
Also effect all mongo commands on a replica set as a timestamp of is returned in the result causing an UnsupportedOperationException to be thrown. Would be preferable in some ways to just ignore the field rather than throw the exception.

**Comment by purplefox** [comment]
I merged #4 but this issue is very confusing as it seems to be talking about several different things:

1. date support
2. support of nulls
3. support all different bson types

So I'm going to close this, but please open new *separate* issues if there are any outstanding issues that still need to be addressed :)
