### ISSUE TITLE
Update doesn't work with ObjectId

### ISSUE THREAD

**Issue by sidney3172** [vert-x3/vertx-mongo-client#70]
Hi Team!
option userObjectId is true.
we have document with id : `ObjectId("56e417abab85b51b8b9743ce").`
in case we are trying to find it - it works fine:
`mongo.find(collection, new JsonObject().put("_id" : "56e417abab85b51b8b9743ce"), null, handler).`
`mongo.save`\- works as well,
but update is not wrapping objectId string into `$oid`, and as a result performing empty update.
Fixed by adding manual wrapper to `$oid` before executing the query.

Is this expected behaviour?

**Comment by karianna** [comment]
@johnoliver Q?

**Comment by diabolicallabs** [comment]
Sergey,

Would you be able to provide your update code snippet? 

I wrote some of the code for useObjectId and will gladly have a look at it. 

If memory serves me correctly, I think that you will have to use $oid for anything other than _id on an update. I don't think there is a way for the mongo client to know what you intend for any other attribute.  Since there is no schema, the type can't be inferred.

If nothing else, the documentation I wrote isn't clear on the matter. Looks like it has a formatting issue as well. :(

**Comment by llfbandit** [comment]
See #45, it should fix this.
